dev:
  server:
    port : 8005 #port where dev application are running
  env:
    platform : browser
    debug : true
  client :
    apiUrl : //localhost:8001/
    auth :
      oauthio_key : 9E7SoR97JvCrmryqfLMBC5Fe5ic
      apiUrl : //localhost:8002/ #//localhost:8002/ #http://ridebetter.info:86/
dev_gce:
  server:
    port : 8005 #port where dev application are running
  env:
    platform : browser
    debug : true
  client :
    apiUrl : http://ridebetter.info:85/
    auth :
      oauthio_key : 9E7SoR97JvCrmryqfLMBC5Fe5ic
      apiUrl : http://ridebetter.info:86/
debug:
  server:
    port : 8005 #port where dev application are running
  env:
    platform : browser
    debug : true
  client :
    apiUrl : //localhost:8001/
    auth :
      oauthio_key : 9E7SoR97JvCrmryqfLMBC5Fe5ic
      apiUrl : //localhost:8002/
stage:
  server:
    port : 8000
  env:
    platform : browser
    debug : false
  client :
    apiUrl :  //ride-better-web-api.herokuapp.com/
    auth :
      apiUrl : //auth-server-oauthio.herokuapp.com/
      oauthio_key : 9E7SoR97JvCrmryqfLMBC5Fe5ic
cordova_dev:
  env:
    platform : cordova
    debug : true
    weinreUrl : 172.30.99.102:9090
  client :
    apiUrl : http://ride-better-web-api.herokuapp.com/
    auth :
      oauthio_key : 9E7SoR97JvCrmryqfLMBC5Fe5ic
      apiUrl : http://auth-server-oauthio.herokuapp.com/
cordova_stage:
  env:
    platform : cordova
    debug : false
  client :
    apiUrl : http://ride-better-web-api.herokuapp.com/
    auth :
      oauthio_key : 9E7SoR97JvCrmryqfLMBC5Fe5ic
      apiUrl : http://auth-server-oauthio.herokuapp.com/
gce_stage:
  server:
    port : 8080
  env:
    platform : browser
    debug : false
  client :
    apiUrl : http://ridebetter.info:85/
    auth :
      apiUrl :  http://ridebetter.info:86/
      oauthio_key : 9E7SoR97JvCrmryqfLMBC5Fe5ic
cordova_gce:
  env:
    platform : cordova
    debug : false
  client :
    apiUrl : http://ridebetter.info:85/
    auth :
      oauthio_key : 9E7SoR97JvCrmryqfLMBC5Fe5ic
      apiUrl : http://ridebetter.info:86/
