app.constant "res_ru",
  "Send" : "Отправить"
  "Cancel" : "Отменить"
  "Add Message" : "Добавить сообщение"
  "Add New" : "Добавить"
  "Snow" : "Снег"
  "Min" : "Мин"
  "Max" : "Макс"
  "Report" : "Сообщить"
  "Closed" : "Закрыто"
  "very little snow" : "очень мало снега"
  "not enough snow" : "недостаточно снега"
  "enough snow" : "снега дотаточно"
  "much snow" : "много снега"
  "lots of snow" : "очень много снега"
  "snow does not fall out" : "снег не выпадал"
  "not much snow fell" : "выпало немного снега"
  "dropped enough snow" : "выпало достаточно снега"
  "much snow fell" : "выпало много снега"
  "lots of snow fell" : "выпало очень много снега"
  "very few people" : "очень мало людей"
  "few people" : "мало людей"
  "enough people" : "достаточно люей"
  "many people" : "много людей"
  "too many people" : "очень много людей"
  "Crowd ?" : "Сколько  ?"
  "Snowing ?" : "Идет Снег ?"
  "Snow on traks ?" : "Снег на Трассах ?"
  "Name" : "Имя"
  "Home" : "Дом"
  "Language" : "Язык"
  "Units" : "Измерения"
  "Reset" : "Сбросить"
  "Login" : "Войти"
  "Logout" : "Выйти"
  "My Info" : "Профайл"
  "Favorites" : "Избранное"
  "Me" : "Профайл"