app.constant "res_fr",
  home : "Maison"
  favorites : "Favoris"
  me : "Moi"
  surf : "Surf !"
  dunno : "Ne sais pas"
  nosurf : "Pas de surf"
  swell : "Houle"
  period : "Période"
  wind : "Vent"
  addnew : "Ajouter"
  search : "Recherche"
  cancel : "Annuler"
  myinfo : "Mes Infos"
  homebeach : "Plage de Maison"
  units : "Unidades"
  eu : "Europe"
  uk : "Royaume-Uni"
  us : "États-Unis"
  reset : "Reset"
  login : "Entrer"
  logout : "Sortie"
  authreqcaption : "Authentification nécessaire"
  authreqtext : "Pour accomplir cette action, vous devez vous connecter à votre compte facebook . Connectez?"
  ok : "OK"
  msgsent : "Vous rapport envoyé !"
  addmssg : "ajouter un message ici"
  send : "Envoyer"
  select : "Sélectionner"
  coldwater : "eau froide"
  crowdalert : "alerte de la foule"
  eventalert : "alerte d'événement"
  strongwaves : "de fortes vagues"
  weakwaves : "vagues faibles"
  reportfirst : "Premier Rapport"
  name : "Nom"
  langen : "Anglais"
  langpt : "Portugais"
  langes : "Espagnol"
  langfr : "Frances"
  lang : "Langue"







