app.constant "res_en",
  home : "Home"
  favorites : "Favorites"
  me : "Me"
  closed : "Closed"
  report : "Report"
  surf : "Surf !"
  dunno : "I dunno"
  nosurf : "No surf"
  swell : "Swell"
  period : "Period"
  wind : "Wind"
  addnew : "Add New"
  search : "Search"
  cancel : "Cancel"
  myinfo : "My Info"
  homebeach : "Home"
  units : "Units"
  eu : "Europe"
  uk : "United Kingdom"
  us : "United States"
  reset : "Reset"
  login : "Login"
  logout : "Logout"
  authreqcaption : "Authentication needed"
  authreqtext : "To do this action you need connect your facebook account. Connect?"
  ok : "OK"
  msgsent : "You report sent !"
  addmssg : "add message here"
  send : "Send"
  select : "Select"
  coldwater : "cold water"
  crowdalert : "crowd alert"
  eventalert : "event alert"
  strongwaves : "strong waves"
  weakwaves : "weak waves"
  reportfirst : "Report First"
  name : "Name"
  langen : "English"
  langpt : "Portuguese"
  langfr : "Frances"
  langes : "Spanish"
  lang : "Language"







