app.constant "res_es",
  home : "Casa"
  favorites : "Favoritos"
  me : "Yo"
  surf : "Surf !"
  dunno : "No te saber"
  nosurf : "Ninguna de surf"
  swell : "Hinchar"
  period : "Período"
  wind : "Viento"
  addnew : "Añadir"
  search : "Buscar"
  cancel : "Cancelar"
  myinfo : "Mi Info"
  homebeach : "Playa de Casa"
  units : "Unidades"
  eu : "Europa"
  uk : "Reino Unido"
  us : "Estados Unidos"
  reset : "Reset"
  login : "Entrar"
  logout : "Salir"
  authreqcaption : "Autenticación necesaria"
  authreqtext : "Para terminar esta acción necesitas conectar tu cuenta de Facebook. Conecte ?"
  ok : "OK"
  msgsent : "Usted informe enviado !"
  addmssg : "añada el mensaje aquí"
  send : "Enviar"
  select : "Seleccione"
  coldwater : "agua fría"
  crowdalert : "alerta multitud"
  eventalert : "alerta de evento"
  strongwaves : "fuerte oleaje"
  weakwaves : "olas débiles"
  reportfirst : "Informe Primeiro"
  name : "Nombre"
  langen : "Inglés"
  langpt : "Portugués"
  langes : "Español"
  langfr : "Frances"
  lang : "Idioma"







