app.constant "resources_ru",
  "Send" : "Отправить"
  "Cancel" : "Отменить"
  "Add Message" : "Добавить сообщение"
  "Add New" : "Добавить"
  "Snow" : "Снег"
  "Min" : "Мин"
  "Max" : "Макс"
  "Report" : "Сообщить"
  "Closed" : "Закрыто"
  "very little powder" : "очень мало снега"
  "not enough powder" : "недостаточно снега"
  "enough powder" : "снега дотаточно"
  "much powder" : "много снега"
  "lots of powder" : "очень много снега"
  "snow does not fall out" : "снег не выпадал"
  "not much snow fell" : "выпало немного снега"
  "dropped enough snow" : "выпало достаточно снега"
  "much snow fell" : "выпало много снега"
  "lots of snow fell" : "выпало очень много снега"
  "very few people" : "очень мало людей"
  "few people" : "мало людей"
  "enough people" : "достаточно люей"
  "many people" : "много людей"
  "too many people" : "очень много людей"
  "Crowd ?" : "Сколько людей?"
  "Snowing ?" : "Идет Снег ?"
  "Powder on pistes ?" : "Снег на Трассах ?"
  "Name" : "Имя"
  "Home" : "Дом"
  "Language" : "Язык"
  "Units" : "Измерения"
  "Reset" : "Сбросить"
  "Login" : "Войти"
  "Logout" : "Выйти"
  "My Info" : "Профайл"
  "Favorites" : "Избранное"
  "Me" : "Профайл"
  "Authorization" : "Авторизация"
  "Search" : "Поиск"
  "mi" : "миль"
  "in" : "дм"
  "km" : "км"
  "cm" : "см"
  "Reason" : "Причина"
  "Supposed open date" : "Возможная дата открытия"
  "Europe" : "Европа"
  "United Kingdom" : "Англия"
  "United States" : "Америка"
  "English" : "Английский"
  "Russian" : "Русский"
  "Unknown" : "Неизвестно"
  "Day off" : "Выходной"
  "Off season" : "Сезон закрыт"
  "Some error occurred, please try again later." : "Ошибка! Попробуйте повторить позднее."
  "Error" : "Ошибка"
  "Alert" : "Внимание"
  "dd.mm.yyyy" : "дд.мм.гггг"
  "rain" : "дождь"
  "snow" : "снег"
  "sleet" : "дождь со снегом"
  "hail" : "град"
  "Please input some data to send" : "Пожайлуста введите данные чтобы отправить"
  "Date in wrong format" : "Дата имеет неправильный формат"
  "Talk" : "Разговор"
  "Send Message" : "Отправить сообщение"
  "Message" : "Сообщение"
  "User not logined" : "Пользователь не залогинен"
  "No more images, try again later." : "Больше нет изображений, попробуйте позднее."
  "Today" : "Сегодня"
  "Housing" : "Жильё"
  "Trip" : "Добраться"
  "Food" : "Еда"
  "Shops" : "Магазины"
  "Services" : "Услуги"
  "Snowfall History" : "История осадков"
  "Days" : "Дни"
  "Cumulative" : "Всего"
  "Fall" : "Выпало"
  "Resort" : "Курорт"
  "Info" : "Информация"
  "Back Home" : "Назад домой"
  "Resort Info" : "Информация"
  "Today's Talks" : "Сегодня"
  "Would you like to install native app?" : "Хотите установить нативное приложение на ваш телефон?"
  "Sure" : "Конечно"
  "Not Now" : "Не сейчас"
  "FAQ" : "Вопросы"
  "Ask Question" : "Задать вопрос"
  "Replies" : "Ответы"
  "Reply" : "Ответить"
  "Remove" : "Удалить"
  "Edit" : "Изменить"
  "After delete, item couldn't be restored. Delete?" : "После удаления запись не может быть востановлна. Удалить?"
  "Please input some text" : "Пожайлуста введите текст"
  "New settings will be activated only after reload." : "Новые нсатройки будут активированы только после перезагрузки."
  "Reload" : "Перегрузить"
  "Car" : "Машина"
  "Micro Bus" : "Микроватобус"
  "Bus" : "Автобус"
  "From town" : "Из города"
  "From" : "Из города"
  "Date" : "Дата"
  "Hours" : "Час"
  "Transport Type" : "Тип Транспорта"
  "Price" : "Цена"
  "Phone" : "Телефон"
  "Phone number" : "Телефон"
  "Create transfer" : "Cоздать трансфер"
  "Create" : "Создать"
  "From town is required" : "Из Города - должно быть заполнено"
  "Success" : "Успешно"
  "Fail" : "Ошибка"
  "Success" : "Успешно"
  "Fail" : "Ошибка"
  "Please add some photo" : "Пожайлуста добавьте фото"
  "Please add some title" : "Пожайлуста добавьте заголовок"
  "Please choose some tag" : "Пожайлуста добавьте таг"
  "Lift Prices" : "Цены на подъемник"
  "Rent Prices" : "Цены на прокат"
  "Food Prices" : "Цены на питание"
  "Service Prices" : "Цены на услуги"
  "Title" : "Заголовок"
  "Tag" : "Таг"
  "Attach photo" : "Выбрать фото"
  "Take photo" : "Снять фото"
  "Messages" : "Cообщения"
  "Message" : "Cообщение"
  "Current" : "Текущий"
  "Favorites" : "Избранные"
  "All" : "Все"
  "Forecast" : "Погода"
  "Snowfall" : "Осадки"
  "Transfer" : "Поездка"
  "Question" : "Вопрос"
  "Choose message" : "Выберите сообщение"
  "Reports" : "Отчеты"
  "Add report" : "Добавить отчет"
  "Add transfer" : "Добавить поездку"
  "Priority" : "Важность"
  "Normal" : "Обычное"
  "Important" : "Важное"
  "Contacts" : "Контакты"
  "Webcams" : "Вебкамеры"
  "Maps" : "Карты"
  "Prices" : "Цены"