"use strict"

app.filter "contact", ($sce) ->
  (contact) ->
    icon = "ion-social-rss-outline"
    prefix = ""
    target = "target='_blank'"
    switch contact.type
      when "phone"
        prefix = "tel:"
        icon = "ion-android-call"
        target = ""
      when "site"
        icon = "ion-earth"
      when "vk"
        icon = "ion-happy-outline"
      when "facebook"
        icon = "ion-social-facebook-outline"
      when "instagram"
        icon = "ion-social-facebook-outline"
      when "facebook"
        icon = "ion-social-instagram-outline"
      when "facebook"
        icon = "ion-social-instagram-outline"
      when "skype"
        icon = "ion-social-skype-outline"
      when "email"
        icon = "ion-email"

    "<a href='#{prefix}#{contact.val}' class='calm'><i class='icon #{icon}'></a>"