app.constant "strings_ru",
  "main" : "Главная"
  "info" : "Информация"
  "prices" : "Цены"
  "faq" : "Вопросы"
  "transfer" : "Добраться"
  "user" : "Пользователь"
  "add" : "Добавить"
  "messages" : "Cообщения"
  "send" : "Отправить"
  "cancel" : "Отменить"
  "add_message" : "Добаить сообщение"
  "add_new" : "Добавить новое"
  "snow" : "Снег"
  "min" : "Мин"
  "max" : "Макс"
  "report" : "Отчет"
  "closed" : "Закрыто"
  "very_little_powder" : "очень мало снега"
  "not_enough_powder" : "недостаточно снега"
  "enough_powder" : "достаточно снега"
  "much_powder" : "много снега"
  "lots_of_powder" : "очень много снега"
  "snow_not_fall" : "снег не выпадал"
  "not_much_snow" : "выпало не много снега"
  "enough_snow" : "выпало достаточно снега"
  "much_snow" : "выпало много снега"
  "lots_snow" : "выпало очень много снега"
  "very_few_people" : "очень мало людей"
  "few_people" : "мало людей"
  "enough_people" : "достаточно людей"
  "many_people" : "много людей"
  "too_many people" : "очень много людей"
  "crowd_q" : "Сколько людей ?"
  "snowing_q" : "Снег идет ?"
  "powder_q" : "Снег на трассах ?"
  "name" : "Имя"
  "home" : "Дом"
  "language" : "Язык"
  "units" : "Единицы"
  "reset" : "Сбросить"
  "login" : "Войти"
  "logout" : "Выйти"
  "my_info" : "Профайл"
  "favorites" : "Избранное"
  "profile" : "Профайл"
  "authorization" : "Авторизация"
  "search" : "Поиск"
  "mi" : "ми"
  "in" : "дм"
  "km" : "км"
  "cm" : "см"
  "reason" : "Причина"
  "supposed_open_date" : "Предпологаемая дата открытия"
  "europe" : "Европа"
  "united_kingdom" : "Англия"
  "united_states" : "Америка"
  "english" : "Английский"
  "russian" : "Русский"
  "unknown" : "Неизвестно"
  "day_off" : "Выходной"
  "off_season" : "Сезон закрыт"
  "some_error" : "Произошла ошибка, пожайлуста повтарите позднее"
  "error" : "Ошибка"
  "alert" : "Внимание"
  "dd_mm_yyyy" : "дд.мм.гггг"
  "rain" : "дождь"
  "snow" : "снег"
  "sleet" : "град"
  "hail" : "снег с дождем"
  "please_input_data" : "Пожайлуста введите данные"
  "date_is_wrong" : "Дата имеет неправильный формат"
  "talk" : "Разговор"
  "send_message" : "Отправить сообщение"
  "nessage" : "Сообщение"
  "user_not_logined" : "Пользватель не залогинен"
  "no_more_images" : "Нет больше изображений, попробуйте позднее"
  "today" : "Сегодня"
  "housing" : "Размещение"
  "trip" : "Поездка"
  "food" : "Питание"
  "shops" : "Магазины"
  "services" : "Услуги"
  "snowfall_history" : "Истоия снегопада"
  "days" : "Дни"
  "cumulative" : "Суммарно"
  "fall" : "Выпало"
  "resort" : "Курорт"
  "info" : "Информация"
  "back_home" : "Назад домой"
  "resort_info" : "Информация о курорте"
  "install_native_q" : "Хотите установить мобильное приложение ?"
  "sure" : "Да"
  "not_now" : "Не сейчас"
  "faq" : "Вопросы"
  "ask_question" : "Задать вопрос"
  "replies" : "Ответы"
  "reply" : "Ответ"
  "remove" : "Удалить"
  "edit" : "Изменить"
  "delete_q" : "После удаления данные не могут быть восстановлены. Продолжить?"
  "input_text" : "Пожайлуста введите текст"
  "new_settings_reload" : "новые настройки будут установлены после перезагрузки"
  "reload" : "Перегрузить"
  "car" : "Машина"
  "micro_bus" : "Микро автобус"
  "bus" : "Автобус"
  "from_town" : "Из города"
  "from" : "Из"
  "date" : "Дата"
  "hours" : "Часы"
  "transport_type" : "Тип транспорта"
  "price" : "Цена"
  "phone" : "Телефон"
  "phone_number" : "Номер телефона"
  "create_transfer" : "Создать трансфер"
  "create" : "Создать"
  "from_town_required" : "Из Города - необходимо заполнить"
  "success" : "Успех"
  "fail" : "Ошибка"
  "add_photo" : "Пожайлуста добавьте фото"
  "add_title" : "Пожайлуста добавьте заголовок"
  "choose_tag" : "Пожайлуста выберите таг"
  "lift_prices" : "Цены на подъемник"
  "rent_prices" : "Цены на аренду"
  "food_prices" : "Цены на питание"
  "service_prices" : "Цены на услуги"
  "title" : "Заголовок"
  "tag" : "Таг"
  "attach_photo" : "Добавить фото"
  "take_photo" : "Снять фото"
  "messages" : "Сообщения"
  "message" : "Сообщение"
  "current" : "Текущий"
  "favorites" : "Избранное"
  "all" : "Все"
  "forecast" : "Погода"
  "snowfall" : "Снегопад"
  "transfer" : "Трансфер"
  "question" : "Вопрос"
  "choose_message" : "Выберитеь сообщение"
  "reports" : "Курорты"
  "add_report" : "Добавить сообщение"
  "add_transfer" : "Добавить трансфер"
  "priority" : "Важность"
  "normal" : "Обычное"
  "important" : "Важное"
  "contacts" : "Контакты"
  "webcams" : "Камеры"
  "maps" : "Карты"
  "prices" : "Цены"
  "remove_photo" : "Удалить фото"
  "total_past" : "Суммарно за прошедшие дни"
  "for_day" : "За день"
  "add_price" : "Добавить цену"
  "yes" : "Да"
  "no" : "Нет"
  "message_required" : "Пожайлуста добавьте сообщение"
  "photo_required" : "Пожайлуста добавьте фото"
  "title_required" : "Пожайлуста добавьте заголовок"
  "tag_required" : "Пожайлуста добавьте таг"
  "data_required" : "Пожайлуста введите данные"  
  "lift_prices" : "Цены на подъемники"
  "rent_prices" : "Цены на аренду"
  "food_prices" : "Цены на питание"  
  "rent_prices" : "Цены на услуги"  
  "confirm_delete" : "После удаления данные не могут быть восстановлены. Продолжить?"
  "filter_message" : "Фильтровать сообщения"
  "ok" : "OK"
  "show_messages_for" : "Показывать сообщения для"