app.constant "strings_en",
  "main" : "Main"
  "info" : "Info"
  "prices" : "Prices"
  "faq" : "FAQ"
  "transfer" : "Transfer"
  "user" : "User"
  "add" : "Add Stuff"
  "messages" : "Messages"
  "send" : "Send"
  "cancel" : "Cancel"
  "add_message" : "Add Message"
  "add_new" : "Add New"
  "snow" : "Snow"
  "min" : "Min"
  "max" : "Max"
  "report" : "Report"
  "closed" : "Closed"
  "very_little_powder" : "very little powder"
  "not_enough_powder" : "not enough powder"
  "enough_powder" : "enough powder"
  "much_powder" : "much powder"
  "lots_of_powder" : "lots of powder"
  "snow_not_fall" : "snow does not fall out"
  "not_much_snow" : "not much snow fell"
  "enough_snow" : "dropped enough snow"
  "much_snow" : "much snow fell"
  "lots_snow" : "lots of snow fell"
  "very_few_people" : "very few people"
  "few_people" : "few people"
  "enough_people" : "enough people"
  "many_people" : "many people"
  "too_many people" : "too many people"
  "crowd_q" : "Crowd ?"
  "snowing_q" : "Snowing ?"
  "powder_q" : "Powder on pistes ?"
  "name" : "Name"
  "home" : "Home"
  "language" : "Language"
  "units" : "Units"
  "reset" : "Reset"
  "login" : "Login"
  "logout" : "Logout"
  "my_info" : "My Info"
  "favorites" : "Favorites"
  "profile" : "Me"
  "authorization" : "Authorization"
  "search" : "Search"
  "mi" : "mi"
  "in" : "in"
  "km" : "km"
  "cm" : "cm"
  "reason" : "Rason"
  "supposed_open_date" : "Supposed open date"
  "europe" : "Europe"
  "united_kingdom" : "United Kingdom"
  "united_states" : "United States"
  "english" : "English"
  "russian" : "Russian"
  "unknown" : "Unknown"
  "day_off" : "Day off"
  "off_season" : "Off season"
  "some_error" : "Some error occurred, please try again later"
  "error" : "Error"
  "alert" : "Alert"
  "dd_mm_yyyy" : "dd.mm.yyyy"
  "rain" : "rain"
  "snow" : "snow"
  "sleet" : "sleet"
  "hail" : "hail"
  "please_input_data" : "Please input some data to send"
  "date_is_wrong" : "Date in wrong format"
  "talk" : "Talk"
  "send_message" : "Send Message"
  "nessage" : "Message"
  "user_not_logined" : "User not logined"
  "no_more_images" : "No more images, try again later"
  "today" : "Today"
  "housing" : "Housing"
  "trip" : "Trip"
  "food" : "Food"
  "shops" : "Shops"
  "services" : "Services"
  "snowfall_history" : "Snowfall History"
  "days" : "Days"
  "cumulative" : "Cumulative"
  "fall" : "Fall"
  "resort" : "Resort"
  "info" : "Info"
  "back_home" : "Back Home"
  "resort_info" : "Resort Info"
  "install_native_q" : "Would you like to install native app ?"
  "sure" : "Sure"
  "not_now" : "Not Now"
  "faq" : "FAQ"
  "ask_question" : "Ask Question"
  "replies" : "Replies"
  "reply" : "Reply"
  "remove" : "Remove"
  "edit" : "Edit"
  "delete_q" : "After delete, item couldn't be restored. Delete?"
  "input_text" : "Please input some text"
  "new_settings_reload" : "New settings will be activated only after reload"
  "reload" : "Reload"
  "car" : "Car"
  "micro_bus" : "Micro Bus"
  "bus" : "Bus"
  "from_town" : "From town"
  "from" : "From"
  "date" : "Date"
  "hours" : "Hours"
  "transport_type" : "Transport Type"
  "price" : "Price"
  "phone" : "Phone"
  "phone_number" : "Phone number"
  "create_transfer" : "Create transfer"
  "create" : "Create"
  "from_town_required" : "From town is required"
  "success" : "Success"
  "fail" : "Fail"
  "success" : "Success"
  "add_photo" : "Please add some photo"
  "add_title" : "Please add some title"
  "choose_tag" : "Please choose some tag"
  "lift_prices" : "Lift Prices"
  "rent_prices" : "Rent Prices"
  "food_prices" : "Food Prices"
  "service_prices" : "Service Prices"
  "title" : "Title"
  "tag" : "Tag"
  "attach_photo" : "Attach photo"
  "take_photo" : "Take photo"
  "messages" : "Messages"
  "message" : "Message"
  "current" : "Current"
  "favorites" : "Favorites"
  "all" : "All"
  "forecast" : "Forecast"
  "snowfall" : "Snowfall"
  "transfer" : "Transfer"
  "question" : "Question"
  "choose_message" : "Choose message"
  "reports" : "Reports"
  "add_report" : "Add report"
  "add_transfer" : "Add transfer"
  "priority" : "Priority"
  "normal" : "Normal"
  "important" : "Important"
  "contacts" : "Contacts"
  "webcams" : "Webcams"
  "maps" : "Maps"
  "prices" : "Prices"
  "remove_photo" : "Remove Photo"
  "total_past" : "Total for the past days"
  "for_day" : "For the day"
  "add_price" : "Add Price"
  "yes" : "Yes"
  "no" : "No"
  "message_required" : "Please add some message"
  "photo_required" : "Please add some photo"
  "title_required" : "Please add some title"
  "tag_required" : "Please choose some tag"
  "data_required" : "Please input some data to send"  
  "lift_prices" : "Lift Prices"
  "rent_prices" : "Rent Prices"
  "food_prices" : "Food Prices"  
  "rent_prices" : "Service Prices"  
  "confirm_delete" : "After delete, item couldn't be restored. Delete?"
  "filter_message" : "Filter messages"
  "ok" : "OK"
  "show_messages_for" : "Show messages for"